# Autogenerated wrapper script for databento_julia_jll for aarch64-apple-darwin-julia_version+1.14.0
export libdatabento_jl

using libcxxwrap_julia_jll
using OpenSSL_jll
using Zstd_jll
JLLWrappers.@generate_wrapper_header("databento_julia")
JLLWrappers.@declare_library_product(libdatabento_jl, "@rpath/libdatabento_jl.dylib")
function __init__()
    JLLWrappers.@generate_init_header(libcxxwrap_julia_jll, OpenSSL_jll, Zstd_jll)
    JLLWrappers.@init_library_product(
        libdatabento_jl,
        "lib/libdatabento_jl.dylib",
        nothing,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
