# Autogenerated wrapper script for databento_julia_jll for x86_64-w64-mingw32-cxx11-julia_version+1.12.0
export libdatabento_jl

using libcxxwrap_julia_jll
using OpenSSL_jll
using Zstd_jll
JLLWrappers.@generate_wrapper_header("databento_julia")
JLLWrappers.@declare_library_product(libdatabento_jl, "libdatabento_jl.dll")
function __init__()
    JLLWrappers.@generate_init_header(libcxxwrap_julia_jll, OpenSSL_jll, Zstd_jll)
    JLLWrappers.@init_library_product(
        libdatabento_jl,
        "bin\\libdatabento_jl.dll",
        nothing,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
