# Autogenerated wrapper script for databento_julia_jll for x86_64-linux-gnu-cxx11-julia_version+1.11.1
export libdatabento_jl

using libcxxwrap_julia_jll
using OpenSSL_jll
using Zstd_jll
JLLWrappers.@generate_wrapper_header("databento_julia")
JLLWrappers.@declare_library_product(libdatabento_jl, "libdatabento_jl.so")
function __init__()
    JLLWrappers.@generate_init_header(libcxxwrap_julia_jll, OpenSSL_jll, Zstd_jll)
    JLLWrappers.@init_library_product(
        libdatabento_jl,
        "lib/libdatabento_jl.so",
        nothing,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
